### ISSUE TITLE
Dynamic snippet support

### ISSUE THREAD

**Issue by drwilco** [stephenbasile/vcl_cli#15]
Right now dynamic snippets download as empty files.

There's also no way to create dynamic snippets.

**Comment by carbon198** [comment]
I added this a while ago, but forgot to update here. You can run `vcl snippet create [name] --d` to create a dynamic snippet. You can run `vcl snippet upload [name]` to update a dynamic snippet. The `upload` and `download` commands still do not affect dynamic snippets however.
