### ISSUE TITLE
Change User-Agent header

### ISSUE THREAD

**Issue by philg1** [stephenbasile/vcl_cli#7]
User agent is currently `For those about to POST, we salute you`.
https://github.com/stephenbasile/vcl_cli/blob/b39d9cc7864f3b65d8ab1719357659b6cd942e5d/lib/vcl/fetcher.rb#L11

Perhaps this can this be changed to something a little more descriptive, eg:
`For those about to POST, vcl_cli salutes you`

;)

**Comment by carbon198** [comment]
You're no fun at all! :)

Yes, I will change it.

**Comment by carbon198** [comment]
Corrected in https://github.com/stephenbasile/vcl_cli/commit/5fd50a38d72b803fbbaf3c8945d5cdad60b0ca05
